### ISSUE TITLE
[cri_utf_tool] "Category" is missing after rebuilding ACB

### ISSUE THREAD

**Issue by Hazuki-san** [ThisKwasior/KwasTools#2]
Usually when you make ACB, you should have Category assigned into CUE tracks. But after rebuiling ACB it is missing entirely
# Before
![Image](https://github.com/user-attachments/assets/5c9063ea-ebdd-4116-ab6c-d53afbbb1e15)
# After
![Image](https://github.com/user-attachments/assets/d0b9b411-5dd3-4927-acdc-c760f2b1d4ab)

**Comment by ThisKwasior** [comment]
Yeah, it's one of many issues I've encountered with current implementation of utf tool. I will be rewriting everything related to criware soon, so I'll keep you posted.

**Comment by Hazuki-san** [comment]
Best ACB editing tools yet, keep up the awesome work!

**Comment by ThisKwasior** [comment]
@Hazuki-san just a heads up. My rewrite is nearing completion. All that's left is AWB and ACB command handling and then I'll send a preview build in a comment here

**Comment by ThisKwasior** [comment]
@Hazuki-san Hello, here's a WIP build of utf and awb tools:
[cri_utf_tool.zip](https://github.com/user-attachments/files/20542729/cri_utf_tool.zip)

**Comment by Hazuki-san** [comment]
![Image](https://github.com/user-attachments/assets/fc76ad0e-743e-4d30-b593-d944bfdf4ab7)
Was this supposed to be saved as "xml"?

**Comment by Hazuki-san** [comment]
p2p awb/acb https://drive.google.com/file/d/1ywAKPaM2NZMD0oRpMYaVU00gFtqjB36z/view?usp=sharing

**Comment by ThisKwasior** [comment]
Alright, thanks to your ACB i found some bugs. I fixed them I think. Yay!
[cri_utf_tool_bugfix.zip](https://github.com/user-attachments/files/20555721/cri_utf_tool_bugfix.zip)

**Comment by Hazuki-san** [comment]
Category is still missing after recompling.
![Image](https://github.com/user-attachments/assets/81b92bae-de34-436d-aeff-1032793ec289)

**Comment by Hazuki-san** [comment]
but yes, the tool now exports proper XML.

**Comment by Hazuki-san** [comment]
ADXv2 in case if you want to have a look around: https://drive.google.com/file/d/1IUFRzp4S_gaVYpLyQQrnrpQODU2Ph7ea/view?usp=sharing

**Comment by ThisKwasior** [comment]
Huh, that's weird. Category didn't disappear in other games I tested. Will look into it later today. Please send me the acf as well, thank you

**Comment by Hazuki-san** [comment]
[p17acf.zip](https://github.com/user-attachments/files/20555939/p17acf.zip)

**Comment by MarioTainaka** [comment]
The Cri Atomviewer seems to crash whenever you load the ACB after the ACF has been loaded. This shouldn't happen i'm running the latest version. Also category names can't be seen in any hex editor or notepad++

**Comment by ThisKwasior** [comment]
I feel like my lack of knowledge at the moment doesn't help me fixing the problem. This ACB does seem funky though.
@MarioTainaka's observation makes the file kinda suspicious, but at the moment I can't deny or confirm.
Does the missing category in atom viewer change the behaviour of the game?

**Comment by MarioTainaka** [comment]
> I feel like my lack of knowledge at the moment doesn't help me fixing the problem. This ACB does seem funky though.
> @MarioTainaka's observation makes the file kinda suspicious, but at the moment I can't deny or confirm.
> Does the missing category in atom viewer change the behaviour of the game?

Based on what I know how this works it 100 percent does

**Comment by Hazuki-san** [comment]
Yes, if there was no category assigned the BGM volume bar will no longer work. And basically all the effects will be gone.

**Comment by ThisKwasior** [comment]
@Hazuki-san Hello! Please try the ACB with this build of utf tool

[bin.zip](https://github.com/user-attachments/files/20780967/bin.zip)

**Comment by ThisKwasior** [comment]
@Hazuki-san Hello again! Here's the up to date build of kwastools. Please let me know if everything works. 

[kwastools-wip-29062025.zip](https://github.com/user-attachments/files/20966382/kwastools-wip-29062025.zip)

**Comment by Hazuki-san** [comment]
Okay, I tried exporting original and repacking original and the category seems to be there. I'l see if custom music works.

**Comment by Hazuki-san** [comment]
The game seems to accept ACB just fine and the volume slider works, I'd call this release a success!

**Comment by ThisKwasior** [comment]
Awesome! Closing the issue
